
import { BaseModel } from "./base.model"

export class VoucherProforma extends BaseModel {

    id: Number
    vhp_po_nbr: String
    vhp_ship: String
    vhp_entity: String
    vhp_category: String
    vhp_ord_date: String
    vhp_req_date: String
    vhp_due_date: String
    vhp_rmks: String
    vhp_cr_terms: String
    vhp_fob: String
    
    vhp_shipvia: String
    vhp_partial: Boolean
    vhp_print_so: Boolean
    vhp_inv_nbr: String
    vhp_pr_list: String
    vhp_xslspsn: String
    vhp_source: String
    vhp_xcomm_pct: Number
    vhp_cr_card: String
    vhp_print_pl: Boolean
    vhp_cr_init: String
    vhp_stat: String  
    vhp_disc_pct: Number
    vhp_tax_pct: Number
    vhp_prepaid: Number
    vhp_to_inv: Boolean
    vhp_invoiced: Boolean
    vhp_ar_acct: String
    vhp_ar_cc: String
    vhp_inv_date: String
    vhp_ship_date: String
    vhp_taxable: Boolean
    vhp_cmtindx: Number
    vhp__qad04: Number
    vhp_user1: String
    vhp_user2: String
    vhp_curr: String
    vhp_ex_rate: Number
    vhp_lang: String
    vhp_type: String
    vhp_conf_date: String
    vhp_rev: Number
    vhp_bol: String
    vhp__qad05: Number
    vhp_pst: Boolean
    vhp_fst_id: String
    vhp_amt: Number
    vhp_tax_amt: Number
    vhp_trl1_amt: Number
    vhp_trl1_cd: String
    vhp_trl2_amt: Number
    vhp_trl2_cd: String
    vhp_trl3_amt: Number
    vhp_trl3_cd: String
    vhp_weight: Number
    vhp_weight_um: String
    vhp_size: Number
    vhp_size_um: String
    vhp_cartons: Number
    vhp_site: String
    vhp_pst_id: String
    vhp_cncl_date: String
    vhp_quote: String
    vhp_taxc: String
  
    vhp_credit: Boolean
    vhp_inv_cr: String
    vhp_project: String
    vhp_channel: String
    vhp_pst_pct: Number
    vhp_fr_list: String
    vhp_fr_terms: String
    vhp_slspsn: String
    vhp_comm_pct: Number
    vhp_inv_mthd: String
    vhp_fix_rate: Boolean
    vhp_ent_ex: Number
    vhp_vend: String
    vhp_print_bl: Boolean
    vhp_userid: String
    vhp_tax_date: String
    vhp_fsm_type: String
    vhp_conrep: String
    vhp_bank: String
    vhp_tax_env: String
    vhp_sched: Boolean
    vhp_fr_min_wt: Number
    vhp_pr_list2: String
    vhp_tax_usage: String
    vhp_sa_nbr: String
    vhp_fix_pr: Boolean
    vhp_sch_mthd: String
    vhp_pricing_dt: String
    vhp_priced_dt: String
    vhp_ca_nbr: String
    vhp_eng_code: String
    vhp_fcg_code: String
    vhp_ship_eng: Boolean
    vhp_crprlist: String
    vhp_auth_days: Number
    vhp_cum_acct: Boolean
    vhp_merge_rss: Boolean
    vhp_ship_cmplt: Number
    vhp_bump_all: Boolean
    vhp_primary: Boolean
    vhp_cust_po: String
    vhp_secondary: Boolean
    vhp_ship_po: String
    vhp_ex_rate2: Number
    vhp_ex_ratetype: String
    vhp_div: String
    vhp_exru_seq: Number
    vhp_app_owner: String
    vhp_ar_sub: String
    vhp_seq_order: Boolean
    vhp_inc_in_rss: Boolean
    vhp_firm_seq_days: Number
    vhp_prep_tax: Number
    vhp__qadl04: Boolean
    vhp_custref_val: Boolean
    vhp_consignment: Boolean
    vhp_max_aging_days: Number
    vhp_consign_loc: String
    vhp_intrans_loc: String
    vhp_auto_replenish: Boolean
    vhp_revenue: String
    vhp_fsaccr_acct: String
    vhp_fsaccr_sub: String
    vhp_fsaccr_cc: String
    vhp_fsdef_acct: String
    vhp_fsdef_sub: String
    vhp_fsdef_cc: String
    vhp_manual_fr_terms: Boolean
    vhp_domain: String
    oid_vhp_mstr: Number
    vhp_req_time: String
}
